version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unitinventory
    # env_file: .env
    environment:
      - PORT=3000
    restart: always
    # depends_on:
    #   - mongodb
    ports:
      - "3000:3000"
#   mongodb:
#     image: mongo
#     restart: always
#     env_file:
#       - ./mongo.env
#     volumes:
#       - mongo-db:/data/db
# volumes:
#   mongo-db:

# since I'm using mongoDb cloud to store my data , there's no need adding mongodb container as a service

