version: "3.9"
services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: unitinventory/v1
    env_file: .env
    restart: always
    depends_on:
      - mongodb
    ports:
      - '3001:3001' 
  mongodb:
    image: mongo
    restart: always
    env_file: 
      - ./mongo.env
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:


